apiVersion: v1
kind: ConfigMap
metadata:
  name: tentacle-plc1-nginx-conf
  namespace: edge-playground
data:
  nginx.conf: |
    server {
      listen 80;
      listen [::]:80;
      server_name _;
    
      location /api/ {
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
    
        proxy_set_header Upgrade                $http_upgrade;
        proxy_set_header Connection             "Upgrade";
        proxy_set_header Host                   $host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;
        proxy_set_header X-Forwarded-Host       $host;
        proxy_set_header X-Forwarded-Port       $server_port;
    
        proxy_pass http://tentacle-plc1:4000/;
      }
    
      location / {
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
    
        proxy_set_header Upgrade                $http_upgrade;
        proxy_set_header Connection             "Upgrade";
        proxy_set_header Host                   $host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;
        proxy_set_header X-Forwarded-Host       $host;
        proxy_set_header X-Forwarded-Port       $server_port;
    
        proxy_pass http://tentacle-plc1-front:3000/;
      }

      location /codeserver/ {
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
    
        proxy_set_header Upgrade                $http_upgrade;
        proxy_set_header Connection             "Upgrade";
        proxy_set_header Host                   $host;
        proxy_set_header X-Real-IP              $remote_addr;
        proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto      $scheme;
        proxy_set_header X-Forwarded-Host       $host;
        proxy_set_header X-Forwarded-Port       $server_port;
    
        proxy_pass http://tentacle-plc1-codeserver:8080/;
      }
    }