apiVersion: batch/v1
kind: CronJob
metadata:
  name: restart-codesys
  namespace: edge-playground
spec:
  concurrencyPolicy: Forbid
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          serviceAccountName: statefulset-restart
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'statefulset/codesys'