apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tentacle-plc1-front
  name: tentacle-plc1-front
  namespace: edge-playground
spec:
  selector:
    matchLabels:
      app: tentacle-plc1-front
  replicas: 1
  template:
    metadata:
      labels:
        app: tentacle-plc1-front
    spec:
      containers:
      - image: joyja/tentacle-plc-front:0.0.10
        name: tentacle-plc1-front
        env:
          - name: TENTACLE_SERVER_HOST
            value: tentacle-plc1
     

