apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tentacle-plc1-front
  name: tentacle-plc1-front
  namespace: edge-playground
spec:
  selector:
    matchLabels:
      app: tentacle-plc1-front
  replicas: 1
  template:
    metadata:
      labels:
        app: tentacle-plc1-front
    spec:
      containers:
      - image: joyja/tentacle-plc-front:v0.0.12
        name: tentacle-plc1-front
        imagePullPolicy: Always
        env:
          - name: TENTACLE_SERVER_HOST
            value: tentacle-plc1
          - name: TENTACLE_CLIENT_PORT
            value: '80'
          - name: TENTACLE_CLIENT_URL
            value: '/api/'
          - name: TENTACLE_CODESERVER_PORT
            value: '80'
          - name: TENTACLE_CODESERVER_URL
            value: '/codeserver/'
     

