apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: statefulset-restart
  namespace: edge-playground
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-codesys
subjects:
  - kind: ServiceAccount
    name: statefulset-restart # important - the name of the service account
    namespace: edge-playground