apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ignition-makers1
  name: ignition-makers1-creds
  namespace: edge-playground
type: Opaque
stringData:
  IGNITION_EDITION: "maker"
  IGNITION_LICENSE_KEY: $IGNITION_MAKERS_1_LICENSE_KEY
  IGNITION_ACTIVATION_TOKEN: $IGNITION_MAKERS_1_ACTIVATION_TOKEN