apiVersion: v1
kind: Secret
metadata:
  labels:
    app: pgadmin1
  name: pgadmin1-creds
  namespace: edge-playground
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: $PGADMIN_1_EMAIL
  PGADMIN_DEFAULT_PASSWORD: $PGADMIN_1_PASSWORD
  # See Postgres Support: https://www.postgresql.org/message-id/CAM9w-_mBpg-5-uEuH4YzSSevSW022RQLBmk5kJSq642f4UE9ug%40mail.gmail.com
  PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
