apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ignition-makers2
  name: ignition-makers2-creds
  namespace: edge-playground
type: Opaque
stringData:
  IGNITION_EDITION: "maker"
  IGNITION_LICENSE_KEY: $IGNITION_MAKERS_2_LICENSE_KEY
  IGNITION_ACTIVATION_TOKEN: $IGNITION_MAKERS_2_ACTIVATION_TOKEN