apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: tentacle-plc1
  name: tentacle-plc1
  namespace: edge-playground
spec:
  selector:
    matchLabels:
      app: tentacle-plc1
  serviceName: tentacle-plc1
  replicas: 1
  template:
    metadata:
      labels:
        app: tentacle-plc1
    spec:
      containers:
      - name: tentacle-plc1
        image: docker.io/joyja/tentacle-plc:v0.0.12
        env: 
        # necessary because we are using cephfs (network file sharing) to
        # share files between code-server and tentacle-plc.
        - name: CHOKIDAR_USEPOLLING
          value: '1'
        volumeMounts:
        - name: tentacle-plc1-pvc
          mountPath: /tentacle/runtime
      initContainers:
      - name: tentacle-plc1-volume-permission-fix
        image: busybox
        command: ["/bin/chmod","-R","777", "/tentacle/runtime"]
        volumeMounts:
        - mountPath: /tentacle/runtime
          name: tentacle-plc1-pvc
  volumeClaimTemplates:
  - metadata:
      name: tentacle-plc1-pvc
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
      storageClassName: csi-cephfs-sc
