apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:
  userID: k8s
  # Make sure you have your environment variables set and pipe the output of envsubst to kubectl apply -f
  userKey: $CEPH_K8S_USER_KEY