apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tentacle-plc1-codeserver
  name: tentacle-plc1-codeserver
  namespace: jar-edge-playground
spec:
  selector:
    matchLabels:
      app: tentacle-plc1-codeserver
  replicas: 1
  template:
    metadata:
      labels:
        app: tentacle-plc1-codeserver
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - image: codercom/code-server:4.5.0
        name: tentacle-plc1-codeserver
        volumeMounts:
          - mountPath: /home/coder/project
            name: tentacle-plc1-pv
      volumes:
      - name: tentacle-plc1-pv
        persistentVolumeClaim:
          claimName: tentacle-plc1-pvc-tentacle-plc1-0
     

